### ISSUE TITLE
BadZipfile: File is not a zip file on Android Python 2.7

### ISSUE THREAD

**Issue by back-to** [livecli/service.livecli.proxy#3]
- [ ] Ignore BadZipfile EXCEPTION
- [ ] Add a zip tester to https://github.com/livecli/plugin.program.liveclitest

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'zipfile.BadZipfile'>
Error Contents: File is not a zip file
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.livecli.proxy/resources/lib/runscript.py", line 37, in <module>
    PLUGINS_UPDATE(manual=True, cleanup=False)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.livecli.proxy/resources/lib/livecli_proxy/side_plugins.py", line 52, in __init__
    self.run()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.livecli.proxy/resources/lib/livecli_proxy/side_plugins.py", line 86, in run
    with ZipFile(temp_zip, 'r') as zip_ref:
  File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-debug/lib/python2.7/zipfile.py", line 770, in __init__
  File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-debug/lib/python2.7/zipfile.py", line 811, in _RealGetContents
BadZipfile: File is not a zip file
-->End of Python script error report<--
```

**Comment by unlocKing** [comment]
Issue has been raised at Kodi:

https://trac.kodi.tv/ticket/17863

**Comment by back-to** [comment]
I used a better way for custom plugins with liveproxy.

**closing**
